version: "1.0"
info:
  model: int-scaffold
packages:
- name: Avivsim_doctor_botProject
  gitServerName: AvivSimDS_GitHub
  gitUrl: https://github.com/AvivSimDS
  gitUsername: AvivSimDS
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:AvivSimOnPremSAGLaptop
  packages:
  - name: Avivsim_doctor_botProject
    version: "1.0"
configurationVariables:
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionEnabled
  : "false"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.dbType
  : MySQL
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.password
  : "{AES}PTWq2hgg4RimZ8H0r79NmA=="
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.databaseName
  : infermedicadb
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.trustStore
  : ""
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.portNumber
  : "3306"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.user
  : root
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.networkProtocol
  : ""
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.driverType
  : MySQLDriverGroup8
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.poolable
  : "false"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.serverName
  : host.docker.internal
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.keyStore
  : ""
