version: "1.0"
info:
  model: int-scaffold
packages:
- name: Avivsim_doctor_botProject
  gitServerName: AvivSimDS_GitHub
  gitUrl: https://github.com/AvivSimDS
  gitUsername: AvivSimDS
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.avivsim_doctor_bot.integrations:AvivSimTestDB_3
  packages:
  - name: Avivsim_doctor_botProject
    version: "1.0"
- serviceName: project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:SelectSingleEvidence
  packages:
  - name: Avivsim_doctor_botProject
    version: "1.0"
configurationVariables:
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.dbType
  : MySQL
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionSettings.portNumber
  : "3306"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.trustStore
  : ""
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.driverType
  : MySQLDriverGroup8
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionSettings.databaseName
  : infermedicadb
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.databaseName
  : infermedicadb
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionSettings.user
  : admin
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionEnabled
  : "false"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionSettings.portNumber
  : "3306"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionSettings.databaseName
  : infermedicadb
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionSettings.serverName
  : host.docker.internal
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionSettings.serverName
  : host.docker.internal
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.password
  : "{AES}PTWq2hgg4RimZ8H0r79NmA=="
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.trustStore
  : ""
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionSettings.networkProtocol
  : ""
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionSettings.user
  : root
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionSettings.trustStore
  : ""
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.networkProtocol
  : ""
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.portNumber
  : "3306"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionManagerSettings.poolable
  : "false"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionSettings.networkProtocol
  : ""
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.poolable
  : "false"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionSettings.password
  : "{AES}PTWq2hgg4RimZ8H0r79NmA=="
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.serverName
  : host.docker.internal
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.keyStore
  : ""
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionSettings.driverType
  : MySQLDriverGroup8
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.keyStore
  : ""
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionSettings.dbType
  : MySQL
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.portNumber
  : "3306"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionEnabled
  : "false"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionSettings.keyStore
  : ""
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.poolable
  : "false"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionSettings.trustStore
  : ""
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.networkProtocol
  : ""
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.driverType
  : MySQLDriverGroup8
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.serverName
  : host.docker.internal
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionEnabled
  : "false"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionManagerSettings.poolable
  : "false"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.databaseName
  : infermedicadb
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.dbType
  : MySQL
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.password
  : "{AES}PTWq2hgg4RimZ8H0r79NmA=="
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionSettings.driverType
  : MySQLDriverGroup8
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.user
  : root
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.user
  : root
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionSettings.keyStore
  : ""
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSimOnPremSAGLaptop.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionEnabled
  : "false"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionSettings.dbType
  : MySQL
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_3.connectionSettings.password
  : "{AES}PTWq2hgg4RimZ8H0r79NmA=="
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.AvivSim_SAG_Laptop_DB.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.Avivsim_doctor_botProject.project.avivsim_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.startupBackoffSecs
  : "10"
